version: '3.8'

services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"

  airflow-init:
    image: apache/airflow:2.9.3
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      # ADDED SECRET KEY HERE
      AIRFLOW__WEBSERVER__SECRET_KEY: "citibike_capstone_secret_key_123456"
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username admin
      --password admin
      --firstname Airflow
      --lastname Admin
      --role Admin
      --email admin@example.com
      "

  airflow-webserver:
    image: apache/airflow:2.9.3
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - F:/Hero Vired/Capstone_project/data:/opt/airflow/data
#      - F:/Hero Vired/Capstone_project/data:/opt/airflow/data
#      - F:/Hero Vired/Capstone_project/data:/opt/airflow/data/raw
#      - F:/Hero Vired/Capstone_project/data:/opt/airflow//data/output
#      - ./data:/opt/airflow/data/raw
#      - ./data:/opt/airflow/data/output
#      - ./data:/opt/airflow/data
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      # ADDED SECRET KEY HERE
      AIRFLOW__WEBSERVER__SECRET_KEY: "citibike_capstone_secret_key_123456"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.9.3
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - F:/Hero Vired/Capstone_project/data:/opt/airflow/data
#      - F:/Hero Vired/Capstone_project/data:/opt/airflow/data
#     - F:/Hero Vired/Capstone_project/data:/opt/airflow/data/raw
#    - F:/Hero Vired/Capstone_project/data:/opt/airflow/data/output
#      - ./data:/opt/airflow/data/raw
#      - ./data:/opt/airflow/data/output
#      - ./data:/opt/airflow/data
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      # ADDED SECRET KEY HERE
      AIRFLOW__WEBSERVER__SECRET_KEY: "citibike_capstone_secret_key_123456"
    command: scheduler